### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#99]
Add markdown files to a `docs/` folder:

update command:
- [ ] using a proxy or alternative cdn. 
- [x] override for versions. see #98
- [ ] using with protractor for directConnect or seleniumAddress related #98 
- [x] set up with microsoft edge

start command:
- [x] override for versions. see #98 
- [ ] using with protractor

other things:
- [x] how it works and where files get downloaded
- [x] help menus

**Comment by moogleberry** [comment]
Since docs are not yet made, does anyone know where files get downloaded to, like the chromedriver and selenium standalone?

**Comment by cnishina** [comment]
The curl calls listed should say the path to the file downloaded. The folder it downloads to is the `selenium/` directory which is located in the webdriver-manager directory.

**Comment by cnishina** [comment]
Obsolete.
